In [1]:
import pandas as pd 
import No_hit
import Fin
pd.set_option("display.max_columns", None)

In [2]:
Bureau        = pd.read_excel(r"C:\Users\HP\OneDrive - JSW\Desktop\DATA(1)_23SEP2026_M2.xlsx", engine = 'calamine', sheet_name = [0,1,2])
Pos           = pd.read_csv(r"C:\Users\HP\OneDrive - JSW\Desktop\RPT_Portfolio_Outstanding__2292026.csv", usecols=['CUST ID', 'Loan Product'], skiprows =2)
OD            = pd.read_excel(r"C:\Users\HP\OneDrive - JSW\Desktop\MODEL RUN\NORTH_SOUTH_OD_Update 2.xlsx", sheet_name = 2, usecols= ['LEAD ID', 'CUST ID'])
inc           = pd.read_excel(r"C:\Users\HP\OneDrive - JSW\Desktop\MODEL RUN\Disbursement Report_Oct 2022 to Aug 2026.xlsx", skiprows = 1)

In [3]:
age =  pd.read_excel(r"C:\Users\HP\OneDrive - JSW\Desktop\DATA(1)_23SEP2026_M2.xlsx", engine = 'calamine', sheet_name=3)
age

      LEAD_ID        DOB
0       92323 1996-02-11
1      155799 1991-01-01
2      231772 1994-01-01
3      236020 1978-01-01
4      272218 1988-01-01
...       ...        ...
2176  3155325 1974-01-01
2177  3155330 1985-01-01
2178  3155338 1987-01-01
2179  3155343 1989-05-08
2180  3155346 1973-07-12

[2181 rows x 2 columns]

In [4]:
age['AGE'] = (pd.Timestamp.now() - age['DOB']).dt.days // 365
age

      LEAD_ID        DOB  AGE
0       92323 1996-02-11   30
1      155799 1991-01-01   35
2      231772 1994-01-01   32
3      236020 1978-01-01   48
4      272218 1988-01-01   38
...       ...        ...  ...
2176  3155325 1974-01-01   52
2177  3155330 1985-01-01   41
2178  3155338 1987-01-01   39
2179  3155343 1989-05-08   37
2180  3155346 1973-07-12   53

[2181 rows x 3 columns]

In [5]:
Bureau[0]['AGE'] = Bureau[0]['LEAD_ID'].map(age.set_index('LEAD_ID')['AGE'])

In [6]:
Bureau[0][Bureau[0]['AGE'].isna()]

Empty DataFrame
Columns: [STATE, DISTRICT_NAME, BRANCH_NAME, LEAD_ID, CCR_CB_DATE, CCR_CREDIT_SCR, Equifax_Risk_SCR, FirstName, LastName, DOB, NO_OF_OTHER_MFI_LENDERS, CCR_MFI_NumberofOpenAccounts, CCR_MFI_NumberofPastDueAccounts, CCR_MFI_TotalPastDueAmount, CCR_MFI_TotalOutstandingBalance, CCR_MFI_MonthlyFamilyIncome, SVAMAAN_COB_INCOME, CCR_MFI_InstallmentAmount, CCR_MFI_RecentAccount, CCR_RETAIL_NumberofOpenAccounts, CCR_RETAIL_InstallmentAmount, CCR_RETAIL_NumberofPastDueAccounts, CCR_RETAIL_TotalPastDueAmount, CCR_RETAIL_TotalOutstandinglBalance, CCR_RETAIL_TotalAccounts, CCR_RETAIL_RecentAccount, CCR_RETAIL_TotalSanctionAmount, CCR_RETAIL_TotalHighCredit, COAPP_RETAIL_CB_DATE, COAPP_CREDIT_SCR, COAPP_FirstName, COAPP_LastName, COAPP_DOB, COAPP_RETAIL_NoOfAccounts, COAPP_RETAIL_NoOfActiveAccounts, COAPP_RETAIL_NoOfWriteOffs, COAPP_RETAIL_TotalPastDue, COAPP_RETAIL_NoOfPastDueAccounts, COAPP_RETAIL_TotalBalanceAmount, COAPP_RETAIL_TotalSanctionAmount, COAPP_RETAIL_TotalCreditLimit, COAPP_RETAIL_TotalMonthlyPaymentAmount, ICUST_ID, COAPP_RELATION, LEAD_STATUS, STAGE, STATUS_DATE, LOAN CYCLE, LOAN_AMT, PROPOSED_EWI, COB_CAMS_FOIR, AGM_FINAL_FOIR, ASSET_TYPE, Total_No_Open_Accounts, Total_Past_due_Accounts, Total_Outstanding_Balance, Total_Installment_Amount, SANCTION_AMT, WRITTEN_OFF_COUNT, ACM_WriteOffAmount, SANCTION_AMT_R, WRITTEN_OFF_COUNT_R, ACR_WriteOffAmount, AGE]
Index: []

In [7]:
EMI, CV, OT, Las, pdt = No_hit.Foir_Model(Bureau, Pos, OD_list= OD, inc=inc, eval_all='Yes')

Processing date: 2026-09-23
CB filtered
Summary filtered

C:\Users\HP\anaconda3\Lib\site-packages\numpy_financial\_financial.py:226: RuntimeWarning: divide by zero encountered in divide
  return -(fv + pv*temp) / fact
C:\Users\HP\anaconda3\Lib\site-packages\numpy_financial\_financial.py:226: RuntimeWarning: divide by zero encountered in divide
  return -(fv + pv*temp) / fact

EMI rows     : 13146, unique leads: 2083
LAS rows     : 13146, unique leads: 2083
CV rows      : 2181, unique leads: 2181
CV rows      : 2181, unique leads: 2181
OT rows      : 2181, unique leads: 2181

============================================================
 DEBUG REPORT FOR LEADS: [525925]
============================================================
============================================================

Output Modified
Comments
Approve After Income Reassessment    774
Approve                              712
FOIR                                 604
Approve After IC- MT                  36
Poor Credit Score - Approve           23
Overdue&WriteOff - Approve            21
More than 4 Lenders                    4
High Outstanding                       3
More than 3 Lenders                    2
Approve After IC- OD                   1
Overdue&WriteOff - Reject              1
Total                               2181

In [8]:
EMI[(EMI['LEAD_ID'] == 2866728) & (EMI['Loan Category'] == 'SHG Group')]

Empty DataFrame
Columns: [LEAD_ID, Name of the Institution, Account Status, Loan Category, Source, Open Status, Past Due, Current Balance, Sanction Amount, Date Reported, Date Opened, Interest Rate, No Of Installments, Term Frequency, EMI, A/C Closed Check, Final EMI, Include in FOIR, Remarks, Equifax ID, Relation, Joint Account Identifier, Date Closed, Bullet Loan Check, Check Bullet, A9, A10, FOIR10, Remark9, Remark10, Remark_Final, STEP 1, Adjusted EMI, Include in FOIR_l]
Index: []

In [9]:
with pd.ExcelWriter('OT_18SEPT2026_corrected_M2_1135_N_.xlsx') as writer:
    OT.to_excel(writer, sheet_name='Output', index=False)
    Las.to_excel(writer, sheet_name='Loanwise', index=False)